#!/usr/bin/env php
<?php
/**
 * This file is part of Railt package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/Reader.php';


$config = new Reader(__DIR__ . '/config.json');

foreach ($config->getPackages() as $remote => $files) {
    echo 'SYNC ' . $remote . "\n" .
        \str_repeat('-', 80) . "\n";

    $path = $config->clone($remote, \sha1($remote));
    $config->update($path, $files);
    $config->commit($path);
}
