preset: psr2

enabled:
    - align_double_arrow
    - align_equals
    - alpha_ordered_imports
    - binary_operator_spaces
    - combine_consecutive_issets
    - combine_consecutive_unsets
    - concat_with_spaces
    - const_visibility_required
    - declare_equal_normalize
    - declare_strict_types
    - dir_constant
    - function_typehint_space
    - hash_to_slash_comment
    - heredoc_to_nowdoc
    - include
    - is_null
    - short_array_syntax
    - short_list_syntax
    - lowercase_cast
    - magic_constant_casing
    - method_separation
    - modernize_types_casting
    - native_function_casing
    - native_function_invocation
    - new_with_braces
    - no_alias_functions
    - no_blank_lines_after_class_opening
    - no_blank_lines_after_phpdoc
    - no_blank_lines_between_imports
    - no_blank_lines_between_traits
    - no_empty_phpdoc
    - no_empty_comment
    - no_empty_statement
    - no_leading_import_slash
    - no_leading_namespace_whitespace
    - no_null_property_initialization
    - no_php4_constructor
    - no_short_bool_cast
    - no_singleline_whitespace_before_semicolons
    - no_spaces_inside_offset
    - no_spaces_outside_offset
    - no_superfluous_elseif
    - no_trailing_comma_in_singleline_array
    - no_unneeded_control_parentheses
    - no_unneeded_curly_braces
    - no_unneeded_final_method
    - no_unused_imports
    - no_useless_else
    - no_useless_return
    - no_whitespace_before_comma_in_array
    - no_whitespace_in_blank_line
    - normalize_index_brace
    - not_operator_with_successor_space
    - object_operator_without_whitespace
    - php_unit_construct
    - php_unit_fqcn_annotation
    - php_unit_namespaced
    - php_unit_strict
    - phpdoc_add_missing_param_annotation
    - phpdoc_link_to_see
    - phpdoc_no_package
    - phpdoc_no_useless_inheritdoc
    - phpdoc_property
    - phpdoc_return_self_reference
    - phpdoc_scalar
    - phpdoc_trim
    - phpdoc_type_to_var
    - phpdoc_single_line_var_spacing
    - pre_increment
    - pow_to_exponentiation
    - print_to_echo
    - random_api_migration
    - return_type_declaration
    - self_accessor
    - short_scalar_cast
    - semicolon_after_instruction
    - simplified_null_return
    - single_quote
    - space_after_semicolon
    - standardize_not_equals
    - ternary_operator_spaces
    - ternary_to_null_coalescing
    - trailing_comma_in_multiline_array
    - trim_array_spaces
    - unary_operator_spaces
    - void_return
    - whitespace_after_comma_in_array
