<?php
/**
 * This file is part of Railt package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

namespace Railt\Tests\Parser;

use Railt\Lexer\Driver\NativeRegex;
use Railt\Lexer\LexerInterface;
use Railt\Parser\Driver\Llk;
use Railt\Parser\Driver\Stateful;
use Railt\Parser\Grammar;
use Railt\Parser\ParserInterface;
use Railt\Parser\Rule\Alternation;
use Railt\Parser\Rule\Concatenation;
use Railt\Parser\Rule\Repetition;
use Railt\Parser\Rule\Terminal;

/**
 * Class SdlLlk
 */
class SdlLlk extends Stateful
{
    /**
     * @return ParserInterface
     * @throws \Railt\Parser\Exception\GrammarException
     */
    protected function boot(): ParserInterface
    {
        return new Llk($this->getLexer(), new Grammar([
            new Repetition(0, 0, -1, 'Directive', null),
            new Repetition(1, 0, -1, 'Definition', null),
            (new Concatenation('Document', [0, 1], 'Document'))->setDefaultId('Document'),
            new Alternation('Definition', ['ObjectDefinition', 'InterfaceDefinition', 'EnumDefinition', 'UnionDefinition', 'SchemaDefinition', 'ScalarDefinition', 'InputDefinition', 'ExtendDefinition', 'DirectiveDefinition'], null),
            new Terminal(4, 'T_BOOL_TRUE', true),
            new Terminal(5, 'T_BOOL_FALSE', true),
            new Terminal(6, 'T_NULL', true),
            new Alternation('ValueKeyword', [4, 5, 6], null),
            new Terminal(8, 'T_ON', true),
            new Terminal(9, 'T_TYPE', true),
            new Terminal(10, 'T_TYPE_IMPLEMENTS', true),
            new Terminal(11, 'T_ENUM', true),
            new Terminal(12, 'T_UNION', true),
            new Terminal(13, 'T_INTERFACE', true),
            new Terminal(14, 'T_SCHEMA', true),
            new Terminal(15, 'T_SCHEMA_QUERY', true),
            new Terminal(16, 'T_SCHEMA_MUTATION', true),
            new Terminal(17, 'T_SCHEMA_SUBSCRIPTION', true),
            new Terminal(18, 'T_SCALAR', true),
            new Terminal(19, 'T_DIRECTIVE', true),
            new Terminal(20, 'T_INPUT', true),
            new Terminal(21, 'T_EXTEND', true),
            new Alternation('Keyword', [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], null),
            new Terminal('Number', 'T_NUMBER_VALUE', true),
            new Terminal('Nullable', 'T_NULL', true),
            new Terminal(25, 'T_BOOL_TRUE', true),
            new Terminal(26, 'T_BOOL_FALSE', true),
            new Alternation('Boolean', [25, 26], null),
            new Terminal(28, 'T_MULTILINE_STRING', true),
            new Terminal(29, 'T_STRING', true),
            new Alternation('String', [28, 29], null),
            new Terminal(31, 'T_NAME', true),
            new Alternation('Word', [31, 'ValueKeyword'], null),
            new Terminal(33, 'T_SCHEMA_QUERY', true),
            new Concatenation(34, [33], 'Name'),
            new Terminal(35, 'T_SCHEMA_MUTATION', true),
            new Concatenation(36, [35], 'Name'),
            new Terminal(37, 'T_SCHEMA_SUBSCRIPTION', true),
            new Concatenation(38, [37], 'Name'),
            new Concatenation(39, ['Word'], 'Name'),
            (new Alternation('Name', [34, 36, 38, 39], null))->setDefaultId('Name'),
            new Alternation(41, ['String', 'Word', 'Keyword'], null),
            new Concatenation('Key', [41], 'Name'),
            new Alternation(43, ['String', 'Number', 'Nullable', 'Keyword', 'Object', 'List', 'Word'], null),
            new Concatenation('Value', [43], 'Value'),
            new Concatenation('ValueDefinition', ['ValueDefinitionResolver'], null),
            new Terminal(46, 'T_NON_NULL', true),
            new Repetition(47, 0, 1, 46, null),
            new Concatenation(48, ['ValueListDefinition', 47], 'List'),
            new Terminal(49, 'T_NON_NULL', true),
            new Repetition(50, 0, 1, 49, null),
            new Concatenation(51, ['ValueScalarDefinition', 50], 'Type'),
            new Alternation('ValueDefinitionResolver', [48, 51], null),
            new Terminal(53, 'T_BRACKET_OPEN', false),
            new Terminal(54, 'T_NON_NULL', true),
            new Repetition(55, 0, 1, 54, null),
            new Concatenation(56, ['ValueScalarDefinition', 55], 'Type'),
            new Terminal(57, 'T_BRACKET_CLOSE', false),
            new Concatenation('ValueListDefinition', [53, 56, 57], null),
            new Alternation('ValueScalarDefinition', ['Keyword', 'Word'], null),
            new Terminal(60, 'T_BRACE_OPEN', false),
            new Repetition(61, 0, -1, 'ObjectPair', null),
            new Terminal(62, 'T_BRACE_CLOSE', false),
            new Concatenation('Object', [60, 61, 62], 'Object'),
            new Terminal(64, 'T_COLON', false),
            new Concatenation('ObjectPair', ['Key', 64, 'Value'], 'ObjectPair'),
            new Terminal(66, 'T_BRACKET_OPEN', false),
            new Repetition(67, 0, -1, 'Value', null),
            new Terminal(68, 'T_BRACKET_CLOSE', false),
            new Concatenation('List', [66, 67, 68], 'List'),
            new Terminal(70, 'T_MULTILINE_STRING', true),
            new Concatenation('Documentation', [70], 'Description'),
            new Repetition(72, 0, 1, 'Documentation', null),
            new Terminal(73, 'T_SCHEMA', true),
            new Repetition(74, 0, 1, 'Name', null),
            new Repetition(75, 0, -1, 'Directive', null),
            new Terminal(76, 'T_BRACE_OPEN', false),
            new Terminal(77, 'T_BRACE_CLOSE', false),
            (new Concatenation('SchemaDefinition', [72, 73, 74, 75, 76, 'SchemaDefinitionBody', 77], 'SchemaDefinition'))->setDefaultId('SchemaDefinition'),
            new Alternation(79, ['SchemaDefinitionQuery', 'SchemaDefinitionMutation', 'SchemaDefinitionSubscription'], null),
            new Repetition('SchemaDefinitionBody', 0, -1, 79, null),
            new Repetition(81, 0, 1, 'Documentation', null),
            new Terminal(82, 'T_SCHEMA_QUERY', false),
            new Terminal(83, 'T_COLON', false),
            new Concatenation('SchemaDefinitionQuery', [81, 82, 83, 'SchemaDefinitionFieldValue'], 'Query'),
            new Repetition(85, 0, 1, 'Documentation', null),
            new Terminal(86, 'T_SCHEMA_MUTATION', false),
            new Terminal(87, 'T_COLON', false),
            new Concatenation('SchemaDefinitionMutation', [85, 86, 87, 'SchemaDefinitionFieldValue'], 'Mutation'),
            new Repetition(89, 0, 1, 'Documentation', null),
            new Terminal(90, 'T_SCHEMA_SUBSCRIPTION', false),
            new Terminal(91, 'T_COLON', false),
            new Concatenation('SchemaDefinitionSubscription', [89, 90, 91, 'SchemaDefinitionFieldValue'], 'Subscription'),
            new Repetition(93, 0, -1, 'Directive', null),
            new Concatenation('SchemaDefinitionFieldValue', ['ValueDefinition', 93], null),
            new Repetition(95, 0, 1, 'Documentation', null),
            new Terminal(96, 'T_SCALAR', false),
            new Repetition(97, 0, -1, 'Directive', null),
            (new Concatenation('ScalarDefinition', [95, 96, 'Name', 97], 'ScalarDefinition'))->setDefaultId('ScalarDefinition'),
            new Repetition(99, 0, 1, 'Documentation', null),
            new Terminal(100, 'T_INPUT', false),
            new Repetition(101, 0, -1, 'Directive', null),
            new Terminal(102, 'T_BRACE_OPEN', false),
            new Repetition(103, 0, -1, 'InputDefinitionField', null),
            new Terminal(104, 'T_BRACE_CLOSE', false),
            (new Concatenation('InputDefinition', [99, 100, 'Name', 101, 102, 103, 104], 'InputDefinition'))->setDefaultId('InputDefinition'),
            new Repetition(106, 0, 1, 'Documentation', null),
            new Terminal(107, 'T_COLON', false),
            new Repetition(108, 0, 1, 'InputDefinitionDefaultValue', null),
            new Repetition(109, 0, -1, 'Directive', null),
            new Concatenation(110, ['Key', 107, 'ValueDefinition', 108, 109], null),
            new Concatenation('InputDefinitionField', [106, 110], 'Argument'),
            new Terminal(112, 'T_EQUAL', false),
            new Concatenation('InputDefinitionDefaultValue', [112, 'Value'], null),
            new Repetition(114, 0, 1, 'Documentation', null),
            new Terminal(115, 'T_EXTEND', false),
            new Concatenation(116, ['ObjectDefinition'], 'ExtendDefinition'),
            new Concatenation(117, ['InterfaceDefinition'], 'ExtendDefinition'),
            new Concatenation(118, ['EnumDefinition'], 'ExtendDefinition'),
            new Concatenation(119, ['UnionDefinition'], 'ExtendDefinition'),
            new Concatenation(120, ['SchemaDefinition'], 'ExtendDefinition'),
            new Concatenation(121, ['ScalarDefinition'], 'ExtendDefinition'),
            new Concatenation(122, ['InputDefinition'], 'ExtendDefinition'),
            new Concatenation(123, ['DirectiveDefinition'], 'ExtendDefinition'),
            new Alternation(124, [116, 117, 118, 119, 120, 121, 122, 123], null),
            (new Concatenation('ExtendDefinition', [114, 115, 124], null))->setDefaultId('ExtendDefinition'),
            new Repetition(126, 0, 1, 'Documentation', null),
            new Terminal(127, 'T_DIRECTIVE', false),
            new Terminal(128, 'T_DIRECTIVE_AT', false),
            new Repetition(129, 0, -1, 'DirectiveDefinitionArguments', null),
            new Terminal(130, 'T_ON', false),
            new Repetition(131, 1, -1, 'DirectiveDefinitionTargets', null),
            (new Concatenation('DirectiveDefinition', [126, 127, 128, 'Name', 129, 130, 131], 'DirectiveDefinition'))->setDefaultId('DirectiveDefinition'),
            new Terminal(133, 'T_PARENTHESIS_OPEN', false),
            new Repetition(134, 0, -1, 'DirectiveDefinitionArgument', null),
            new Terminal(135, 'T_PARENTHESIS_CLOSE', false),
            new Concatenation('DirectiveDefinitionArguments', [133, 134, 135], null),
            new Repetition(137, 0, 1, 'Documentation', null),
            new Terminal(138, 'T_COLON', false),
            new Repetition(139, 0, 1, 'DirectiveDefinitionDefaultValue', null),
            new Repetition(140, 0, -1, 'Directive', null),
            new Concatenation('DirectiveDefinitionArgument', [137, 'Key', 138, 'ValueDefinition', 139, 140], 'Argument'),
            new Terminal(142, 'T_OR', false),
            new Concatenation(143, [142, 'Key'], null),
            new Repetition(144, 0, -1, 143, null),
            new Concatenation('DirectiveDefinitionTargets', ['Key', 144], 'Target'),
            new Terminal(146, 'T_EQUAL', false),
            new Concatenation('DirectiveDefinitionDefaultValue', [146, 'Value'], null),
            new Repetition(148, 0, 1, 'Documentation', null),
            new Terminal(149, 'T_TYPE', false),
            new Repetition(150, 0, 1, 'ObjectDefinitionImplements', null),
            new Repetition(151, 0, -1, 'Directive', null),
            new Terminal(152, 'T_BRACE_OPEN', false),
            new Repetition(153, 0, -1, 'ObjectDefinitionField', null),
            new Terminal(154, 'T_BRACE_CLOSE', false),
            (new Concatenation('ObjectDefinition', [148, 149, 'Name', 150, 151, 152, 153, 154], 'ObjectDefinition'))->setDefaultId('ObjectDefinition'),
            new Terminal(156, 'T_TYPE_IMPLEMENTS', false),
            new Repetition(157, 0, -1, 'Key', null),
            new Terminal(158, 'T_AND', false),
            new Concatenation(159, [158, 'Key'], null),
            new Repetition(160, 0, 1, 159, null),
            new Concatenation('ObjectDefinitionImplements', [156, 157, 160], 'Implements'),
            new Repetition(162, 0, 1, 'Documentation', null),
            new Repetition(163, 0, 1, 'Arguments', null),
            new Terminal(164, 'T_COLON', false),
            new Concatenation(165, ['Key', 163, 164, 'ObjectDefinitionFieldValue'], null),
            new Concatenation('ObjectDefinitionField', [162, 165], 'Field'),
            new Repetition(167, 0, -1, 'Directive', null),
            new Concatenation('ObjectDefinitionFieldValue', ['ValueDefinition', 167], null),
            new Repetition(169, 0, 1, 'Documentation', null),
            new Terminal(170, 'T_INTERFACE', false),
            new Repetition(171, 0, -1, 'Directive', null),
            new Terminal(172, 'T_BRACE_OPEN', false),
            new Repetition(173, 0, -1, 'InterfaceDefinitionBody', null),
            new Terminal(174, 'T_BRACE_CLOSE', false),
            (new Concatenation('InterfaceDefinition', [169, 170, 'Name', 171, 172, 173, 174], 'InterfaceDefinition'))->setDefaultId('InterfaceDefinition'),
            new Terminal(176, 'T_COLON', false),
            new Repetition(177, 0, -1, 'Directive', null),
            new Concatenation(178, ['InterfaceDefinitionFieldKey', 176, 'ValueDefinition', 177], null),
            new Concatenation('InterfaceDefinitionBody', [178], 'Field'),
            new Repetition(180, 0, 1, 'Documentation', null),
            new Repetition(181, 0, 1, 'Arguments', null),
            new Concatenation('InterfaceDefinitionFieldKey', [180, 'Key', 181], null),
            new Repetition(183, 0, 1, 'Documentation', null),
            new Terminal(184, 'T_ENUM', false),
            new Repetition(185, 0, -1, 'Directive', null),
            new Terminal(186, 'T_BRACE_OPEN', false),
            new Repetition(187, 0, -1, 'EnumField', null),
            new Terminal(188, 'T_BRACE_CLOSE', false),
            (new Concatenation('EnumDefinition', [183, 184, 'Name', 185, 186, 187, 188], 'EnumDefinition'))->setDefaultId('EnumDefinition'),
            new Repetition(190, 0, 1, 'Documentation', null),
            new Repetition(191, 0, -1, 'Directive', null),
            new Concatenation(192, ['EnumValue', 191], null),
            new Concatenation('EnumField', [190, 192], 'Value'),
            new Terminal(194, 'T_NAME', true),
            new Alternation(195, [194, 'Keyword'], null),
            new Concatenation('EnumValue', [195], 'Name'),
            new Repetition(197, 0, 1, 'Documentation', null),
            new Terminal(198, 'T_UNION', false),
            new Repetition(199, 0, -1, 'Directive', null),
            new Terminal(200, 'T_EQUAL', false),
            (new Concatenation('UnionDefinition', [197, 198, 'Name', 199, 200, 'UnionBody'], 'UnionDefinition'))->setDefaultId('UnionDefinition'),
            new Terminal(202, 'T_OR', false),
            new Repetition(203, 0, 1, 202, null),
            new Repetition(204, 1, -1, 'UnionUnitesList', null),
            new Concatenation('UnionBody', [203, 204], 'Relations'),
            new Terminal(206, 'T_OR', false),
            new Concatenation(207, [206, 'Name'], null),
            new Repetition(208, 0, -1, 207, null),
            new Concatenation('UnionUnitesList', ['Name', 208], null),
            new Terminal(210, 'T_PARENTHESIS_OPEN', false),
            new Repetition(211, 0, -1, 'ArgumentPair', null),
            new Terminal(212, 'T_PARENTHESIS_CLOSE', false),
            new Concatenation('Arguments', [210, 211, 212], null),
            new Repetition(214, 0, 1, 'Documentation', null),
            new Terminal(215, 'T_COLON', false),
            new Repetition(216, 0, 1, 'ArgumentDefaultValue', null),
            new Repetition(217, 0, -1, 'Directive', null),
            new Concatenation('ArgumentPair', [214, 'Key', 215, 'ValueDefinition', 216, 217], 'Argument'),
            new Concatenation('ArgumentValue', ['ValueDefinition'], 'Type'),
            new Terminal(220, 'T_EQUAL', false),
            new Concatenation('ArgumentDefaultValue', [220, 'Value'], null),
            new Terminal(222, 'T_DIRECTIVE_AT', false),
            new Repetition(223, 0, 1, 'DirectiveArguments', null),
            (new Concatenation('Directive', [222, 'Name', 223], 'Directive'))->setDefaultId('Directive'),
            new Terminal(225, 'T_PARENTHESIS_OPEN', false),
            new Repetition(226, 0, -1, 'DirectiveArgumentPair', null),
            new Terminal(227, 'T_PARENTHESIS_CLOSE', false),
            new Concatenation('DirectiveArguments', [225, 226, 227], null),
            new Terminal(229, 'T_COLON', false),
            new Concatenation('DirectiveArgumentPair', ['Key', 229, 'Value'], 'Argument'),
        ], 'Document'));
    }

    /**
     * @return LexerInterface
     */
    public function getLexer(): LexerInterface
    {
        return new NativeRegex([
            'T_NON_NULL'            => '!',
            'T_VAR'                 => '\$',
            'T_PARENTHESIS_OPEN'    => '\(',
            'T_PARENTHESIS_CLOSE'   => '\)',
            'T_THREE_DOTS'          => '\.\.\.',
            'T_COLON'               => ':',
            'T_EQUAL'               => '=',
            'T_DIRECTIVE_AT'        => '@',
            'T_BRACKET_OPEN'        => '\[',
            'T_BRACKET_CLOSE'       => '\]',
            'T_BRACE_OPEN'          => '{',
            'T_BRACE_CLOSE'         => '}',
            'T_OR'                  => '\|',
            'T_AND'                 => '\&',
            'T_NUMBER_VALUE'        => '\-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][\+\-]?[0-9]+)?\b',
            'T_BOOL_TRUE'           => 'true\b',
            'T_BOOL_FALSE'          => 'false\b',
            'T_NULL'                => 'null\b',
            'T_MULTILINE_STRING'    => '"""(?:\\\"""|(?!""").|\s)*"""',
            'T_STRING'              => '"[^"\\\]*(\\\.[^"\\\]*)*"',
            'T_EXTENDS'             => 'extends\b',
            'T_TYPE_IMPLEMENTS'     => 'implements\b',
            'T_ON'                  => 'on\b',
            'T_TYPE'                => 'type\b',
            'T_ENUM'                => 'enum\b',
            'T_UNION'               => 'union\b',
            'T_INTERFACE'           => 'interface\b',
            'T_SCHEMA'              => 'schema\b',
            'T_SCHEMA_QUERY'        => 'query\b',
            'T_SCHEMA_MUTATION'     => 'mutation\b',
            'T_SCHEMA_SUBSCRIPTION' => 'subscription\b',
            'T_SCALAR'              => 'scalar\b',
            'T_DIRECTIVE'           => 'directive\b',
            'T_INPUT'               => 'input\b',
            'T_EXTEND'              => 'extend\b',
            'T_NAME'                => '([_A-Za-z][_0-9A-Za-z]*)',
            'T_VARIABLE'            => '(\$[_A-Za-z][_0-9A-Za-z]*)',
            'skip'                  => '(?:(?:[\xfe\xff|\x20|\x09|\x0a|\x0d]+|#[^\n]*)|,)',
        ], ['skip']);
    }
}
