<?php

/**
 * This file is part of Railt package and has been autogenerated.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://github.com/railt/sdl/blob/2.0.x-dev/LICENSE.md
 * @see https://github.com/phplrt/parser/blob/2.2.3/LICENSE.md
 * @see https://github.com/phplrt/lexer/blob/2.2.3/LICENSE.md
 */

declare(strict_types=1);

namespace Railt\SDL;

use Phplrt\Contracts\Source\ReadableInterface;
use Phplrt\Parser\Buffer\BufferInterface;
use Phplrt\Parser\Exception\ParserRuntimeException;
use Phplrt\Parser\Parser as BaseParser;
use Phplrt\Parser\Rule\Alternation;
use Phplrt\Parser\Rule\Concatenation;
use Phplrt\Parser\Rule\Lexeme;
use Phplrt\Parser\Rule\Optional;
use Phplrt\Parser\Rule\Repetition;
use Phplrt\Parser\Rule\RuleInterface;
use Phplrt\Source\File;
use Railt\SDL\Ast\Location;
use Railt\SDL\Ast\Node;
use Railt\SDL\Exception\SyntaxErrorException;
use Railt\SDL\Parser\Builder;
use Railt\SDL\Parser\Lexer;

/**
 * This class is generated by railt/parser, specifically
 * by Railt\SDL\Parser\Generator\Generator.
 */
final class Parser extends BaseParser
{
    /**
     * @var string
     */
    private const ROOT_PRODUCTION = 'Document';

    /**
     * Parser constructor.
     */
    public function __construct()
    {
        parent::__construct(new Lexer(), $this->grammar(), [
            parent::CONFIG_AST_BUILDER  => new Builder(),
            parent::CONFIG_INITIAL_RULE => self::ROOT_PRODUCTION,
        ]);
    }

    /**
     * @return array|RuleInterface[]
     */
    private function grammar(): array
    {
        return [
            0 => new Lexeme(
                'T_TRUE',
                true,
            ),
            1 => new Lexeme(
                'T_FALSE',
                true,
            ),
            2 => new Lexeme(
                'T_NULL',
                true,
            ),
            3 => new Lexeme(
                'T_TYPE',
                true,
            ),
            4 => new Lexeme(
                'T_ENUM',
                true,
            ),
            5 => new Lexeme(
                'T_UNION',
                true,
            ),
            6 => new Lexeme(
                'T_INTERFACE',
                true,
            ),
            7 => new Lexeme(
                'T_SCHEMA',
                true,
            ),
            8 => new Lexeme(
                'T_SCALAR',
                true,
            ),
            9 => new Lexeme(
                'T_DIRECTIVE',
                true,
            ),
            10 => new Lexeme(
                'T_INPUT',
                true,
            ),
            11 => new Lexeme(
                'T_EXTEND',
                true,
            ),
            12 => new Lexeme(
                'T_EXTENDS',
                true,
            ),
            13 => new Lexeme(
                'T_IMPLEMENTS',
                true,
            ),
            14 => new Lexeme(
                'T_ON',
                true,
            ),
            15 => new Lexeme(
                'T_REPEATABLE',
                true,
            ),
            16 => new Lexeme(
                'T_QUERY',
                true,
            ),
            17 => new Lexeme(
                'T_MUTATION',
                true,
            ),
            18 => new Lexeme(
                'T_SUBSCRIPTION',
                true,
            ),
            19 => new Lexeme(
                'T_NAME',
                true,
            ),
            20 => new Alternation(
                [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
            ),
            21 => new Concatenation(
                [20],
            ),
            22 => new Concatenation(
                [28, 29],
            ),
            23 => new Concatenation(
                [26, 25, 27],
            ),
            24 => new Concatenation(
                [21],
            ),
            25 => new Alternation(
                [22, 23, 24],
            ),
            26 => new Lexeme(
                'T_BRACKET_OPEN',
                false,
            ),
            27 => new Lexeme(
                'T_BRACKET_CLOSE',
                false,
            ),
            28 => new Alternation(
                [23, 24],
            ),
            29 => new Lexeme(
                'T_NON_NULL',
                false,
            ),
            30 => new Lexeme(
                'T_FALSE',
                true,
            ),
            31 => new Lexeme(
                'T_TRUE',
                true,
            ),
            32 => new Alternation(
                [30, 31],
            ),
            33 => new Concatenation(
                [20],
            ),
            34 => new Repetition(
                41,
                0,
                INF,
            ),
            35 => new Lexeme(
                'T_BRACKET_OPEN',
                false,
            ),
            36 => new Lexeme(
                'T_BRACKET_CLOSE',
                false,
            ),
            37 => new Concatenation(
                [35, 34, 36],
            ),
            38 => new Alternation(
                [59, 60, 37, 50],
            ),
            39 => new Lexeme(
                'T_COMMA',
                false,
            ),
            40 => new Optional(
                39,
            ),
            41 => new Concatenation(
                [38, 40],
            ),
            42 => new Lexeme(
                'T_NULL',
                false,
            ),
            43 => new Lexeme(
                'T_INT',
                true,
            ),
            44 => new Lexeme(
                'T_FLOAT',
                true,
            ),
            45 => new Lexeme(
                'T_FLOAT_EXP',
                true,
            ),
            46 => new Alternation(
                [44, 45],
            ),
            47 => new Repetition(
                51,
                0,
                INF,
            ),
            48 => new Lexeme(
                'T_BRACE_OPEN',
                false,
            ),
            49 => new Lexeme(
                'T_BRACE_CLOSE',
                false,
            ),
            50 => new Concatenation(
                [48, 47, 49],
            ),
            51 => new Concatenation(
                [20, 53, 38, 54],
            ),
            52 => new Lexeme(
                'T_COMMA',
                false,
            ),
            53 => new Lexeme(
                'T_COLON',
                false,
            ),
            54 => new Optional(
                52,
            ),
            55 => new Lexeme(
                'T_BLOCK_STRING',
                true,
            ),
            56 => new Lexeme(
                'T_STRING',
                true,
            ),
            57 => new Alternation(
                [55, 56],
            ),
            58 => new Lexeme(
                'T_VARIABLE',
                true,
            ),
            59 => new Concatenation(
                [58],
            ),
            60 => new Alternation(
                [43, 46, 57, 32, 42, 33],
            ),
            61 => new Optional(
                57,
            ),
            62 => new Concatenation(
                [64, 66],
            ),
            63 => new Concatenation(
                [61, 62],
            ),
            64 => new Concatenation(
                [68, 69],
            ),
            65 => new Concatenation(
                [71, 72, 73],
            ),
            66 => new Optional(
                65,
            ),
            67 => new Repetition(
                208,
                1,
                INF,
            ),
            68 => new Lexeme(
                'T_SCHEMA',
                false,
            ),
            69 => new Optional(
                67,
            ),
            70 => new Repetition(
                77,
                1,
                INF,
            ),
            71 => new Lexeme(
                'T_BRACE_OPEN',
                false,
            ),
            72 => new Optional(
                70,
            ),
            73 => new Lexeme(
                'T_BRACE_CLOSE',
                false,
            ),
            74 => new Concatenation(
                [78, 79, 24],
            ),
            75 => new Lexeme(
                'T_COMMA',
                false,
            ),
            76 => new Optional(
                75,
            ),
            77 => new Concatenation(
                [74, 76],
            ),
            78 => new Alternation(
                [80, 81, 82],
            ),
            79 => new Lexeme(
                'T_COLON',
                false,
            ),
            80 => new Lexeme(
                'T_QUERY',
                true,
            ),
            81 => new Lexeme(
                'T_MUTATION',
                true,
            ),
            82 => new Lexeme(
                'T_SUBSCRIPTION',
                true,
            ),
            83 => new Concatenation(
                [92, 93, 21, 94, 95],
            ),
            84 => new Concatenation(
                [105, 104],
            ),
            85 => new Concatenation(
                [61, 83, 84],
            ),
            86 => new Repetition(
                96,
                1,
                INF,
            ),
            87 => new Lexeme(
                'T_PARENTHESIS_OPEN',
                false,
            ),
            88 => new Optional(
                86,
            ),
            89 => new Lexeme(
                'T_PARENTHESIS_CLOSE',
                false,
            ),
            90 => new Concatenation(
                [87, 88, 89],
            ),
            91 => new Lexeme(
                'T_REPEATABLE',
                true,
            ),
            92 => new Lexeme(
                'T_DIRECTIVE',
                false,
            ),
            93 => new Lexeme(
                'T_DIRECTIVE_AT',
                false,
            ),
            94 => new Optional(
                90,
            ),
            95 => new Optional(
                91,
            ),
            96 => new Concatenation(
                [61, 20, 100, 25, 101, 102, 103],
            ),
            97 => new Lexeme(
                'T_EQUAL',
                false,
            ),
            98 => new Concatenation(
                [97, 38],
            ),
            99 => new Lexeme(
                'T_COMMA',
                false,
            ),
            100 => new Lexeme(
                'T_COLON',
                false,
            ),
            101 => new Optional(
                98,
            ),
            102 => new Optional(
                67,
            ),
            103 => new Optional(
                99,
            ),
            104 => new Concatenation(
                [110, 107, 111],
            ),
            105 => new Lexeme(
                'T_ON',
                false,
            ),
            106 => new Lexeme(
                'T_OR',
                false,
            ),
            107 => new Concatenation(
                [20],
            ),
            108 => new Lexeme(
                'T_OR',
                false,
            ),
            109 => new Concatenation(
                [108, 107],
            ),
            110 => new Optional(
                106,
            ),
            111 => new Repetition(
                109,
                0,
                INF,
            ),
            112 => new Concatenation(
                [61, 20, 120, 121, 25, 122, 123],
            ),
            113 => new Repetition(
                112,
                1,
                INF,
            ),
            114 => new Concatenation(
                [215, 216, 217],
            ),
            115 => new Lexeme(
                'T_PARENTHESIS_OPEN',
                false,
            ),
            116 => new Optional(
                114,
            ),
            117 => new Lexeme(
                'T_PARENTHESIS_CLOSE',
                false,
            ),
            118 => new Concatenation(
                [115, 116, 117],
            ),
            119 => new Lexeme(
                'T_COMMA',
                false,
            ),
            120 => new Optional(
                118,
            ),
            121 => new Lexeme(
                'T_COLON',
                false,
            ),
            122 => new Optional(
                67,
            ),
            123 => new Optional(
                119,
            ),
            124 => new Concatenation(
                [126, 128],
            ),
            125 => new Concatenation(
                [61, 124],
            ),
            126 => new Concatenation(
                [129, 21, 130],
            ),
            127 => new Concatenation(
                [132, 133, 134],
            ),
            128 => new Optional(
                127,
            ),
            129 => new Lexeme(
                'T_ENUM',
                false,
            ),
            130 => new Optional(
                67,
            ),
            131 => new Repetition(
                135,
                1,
                INF,
            ),
            132 => new Lexeme(
                'T_BRACE_OPEN',
                false,
            ),
            133 => new Optional(
                131,
            ),
            134 => new Lexeme(
                'T_BRACE_CLOSE',
                false,
            ),
            135 => new Concatenation(
                [61, 20, 137, 138],
            ),
            136 => new Lexeme(
                'T_COMMA',
                false,
            ),
            137 => new Optional(
                67,
            ),
            138 => new Optional(
                136,
            ),
            139 => new Concatenation(
                [141, 143],
            ),
            140 => new Concatenation(
                [61, 139],
            ),
            141 => new Concatenation(
                [144, 21, 145],
            ),
            142 => new Concatenation(
                [147, 148, 149],
            ),
            143 => new Optional(
                142,
            ),
            144 => new Lexeme(
                'T_INPUT',
                false,
            ),
            145 => new Optional(
                67,
            ),
            146 => new Repetition(
                150,
                1,
                INF,
            ),
            147 => new Lexeme(
                'T_BRACE_OPEN',
                false,
            ),
            148 => new Optional(
                146,
            ),
            149 => new Lexeme(
                'T_BRACE_CLOSE',
                false,
            ),
            150 => new Concatenation(
                [61, 20, 154, 25, 155, 156, 157],
            ),
            151 => new Lexeme(
                'T_EQUAL',
                false,
            ),
            152 => new Concatenation(
                [151, 38],
            ),
            153 => new Lexeme(
                'T_COMMA',
                false,
            ),
            154 => new Lexeme(
                'T_COLON',
                false,
            ),
            155 => new Optional(
                152,
            ),
            156 => new Optional(
                67,
            ),
            157 => new Optional(
                153,
            ),
            158 => new Concatenation(
                [160, 162],
            ),
            159 => new Concatenation(
                [61, 158],
            ),
            160 => new Concatenation(
                [164, 21, 165, 166],
            ),
            161 => new Concatenation(
                [167, 168, 169],
            ),
            162 => new Optional(
                161,
            ),
            163 => new Concatenation(
                [172, 173, 24, 174],
            ),
            164 => new Lexeme(
                'T_INTERFACE',
                false,
            ),
            165 => new Optional(
                163,
            ),
            166 => new Optional(
                67,
            ),
            167 => new Lexeme(
                'T_BRACE_OPEN',
                false,
            ),
            168 => new Optional(
                113,
            ),
            169 => new Lexeme(
                'T_BRACE_CLOSE',
                false,
            ),
            170 => new Alternation(
                [175, 176],
            ),
            171 => new Concatenation(
                [170, 24],
            ),
            172 => new Lexeme(
                'T_IMPLEMENTS',
                false,
            ),
            173 => new Optional(
                170,
            ),
            174 => new Repetition(
                171,
                0,
                INF,
            ),
            175 => new Lexeme(
                'T_COMMA',
                false,
            ),
            176 => new Lexeme(
                'T_AND',
                false,
            ),
            177 => new Concatenation(
                [179, 181],
            ),
            178 => new Concatenation(
                [61, 177],
            ),
            179 => new Concatenation(
                [182, 21, 183, 184],
            ),
            180 => new Concatenation(
                [185, 186, 187],
            ),
            181 => new Optional(
                180,
            ),
            182 => new Lexeme(
                'T_TYPE',
                false,
            ),
            183 => new Optional(
                163,
            ),
            184 => new Optional(
                67,
            ),
            185 => new Lexeme(
                'T_BRACE_OPEN',
                false,
            ),
            186 => new Optional(
                113,
            ),
            187 => new Lexeme(
                'T_BRACE_CLOSE',
                false,
            ),
            188 => new Concatenation(
                [190],
            ),
            189 => new Concatenation(
                [61, 188],
            ),
            190 => new Concatenation(
                [191, 21, 192],
            ),
            191 => new Lexeme(
                'T_SCALAR',
                false,
            ),
            192 => new Optional(
                67,
            ),
            193 => new Concatenation(
                [195, 197],
            ),
            194 => new Concatenation(
                [61, 193],
            ),
            195 => new Concatenation(
                [198, 21, 199],
            ),
            196 => new Concatenation(
                [201, 202],
            ),
            197 => new Optional(
                196,
            ),
            198 => new Lexeme(
                'T_UNION',
                false,
            ),
            199 => new Optional(
                67,
            ),
            200 => new Concatenation(
                [206, 24, 207],
            ),
            201 => new Lexeme(
                'T_EQUAL',
                false,
            ),
            202 => new Optional(
                200,
            ),
            203 => new Lexeme(
                'T_OR',
                false,
            ),
            204 => new Lexeme(
                'T_OR',
                false,
            ),
            205 => new Concatenation(
                [204, 24],
            ),
            206 => new Optional(
                203,
            ),
            207 => new Repetition(
                205,
                0,
                INF,
            ),
            208 => new Concatenation(
                [209, 21, 210],
            ),
            209 => new Lexeme(
                'T_DIRECTIVE_AT',
                false,
            ),
            210 => new Optional(
                114,
            ),
            211 => new Concatenation(
                [20, 218, 38],
            ),
            212 => new Lexeme(
                'T_COMMA',
                false,
            ),
            213 => new Optional(
                212,
            ),
            214 => new Concatenation(
                [211, 213],
            ),
            215 => new Lexeme(
                'T_PARENTHESIS_OPEN',
                false,
            ),
            216 => new Repetition(
                214,
                0,
                INF,
            ),
            217 => new Lexeme(
                'T_PARENTHESIS_CLOSE',
                false,
            ),
            218 => new Lexeme(
                'T_COLON',
                false,
            ),
            219 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            220 => new Concatenation(
                [61, 219, 124],
            ),
            221 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            222 => new Concatenation(
                [61, 221, 139],
            ),
            223 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            224 => new Concatenation(
                [61, 223, 158],
            ),
            225 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            226 => new Concatenation(
                [61, 225, 177],
            ),
            227 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            228 => new Concatenation(
                [61, 227, 188],
            ),
            229 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            230 => new Concatenation(
                [61, 229, 62],
            ),
            231 => new Lexeme(
                'T_EXTEND',
                false,
            ),
            232 => new Concatenation(
                [61, 231, 193],
            ),
            'Document' => new Repetition(
                233,
                0,
                INF,
            ),
            233 => new Alternation(
                [234, 235],
            ),
            234 => new Alternation(
                [63, 85, 236],
            ),
            236 => new Alternation(
                [189, 178, 159, 194, 125, 140],
            ),
            235 => new Alternation(
                [230, 237],
            ),
            237 => new Alternation(
                [228, 226, 224, 232, 220, 222],
            ),
        ];
    }

    /**
     * {@inheritDoc}
     */
    protected function next(ReadableInterface $source, BufferInterface $buffer, $state)
    {
        $from = $buffer->current()->getOffset();

        $result = parent::next($source, $buffer, $state);

        if ($result instanceof Node) {
            $result->loc = new Location($source, $from, $buffer->current()->getOffset());
        }

        return $result;
    }

    /**
     * {@inheritDoc}
     */
    public function parse($source): iterable
    {
        $source = File::new($source);

        try {
            return parent::parse($source);
        } catch (ParserRuntimeException $e) {
            throw new SyntaxErrorException($e->getMessage(), $source, $e->getToken()->getOffset());
        }
    }
}
